# basic configuration
baseurl: 
markdown: redcarpet
permalink: /:categories/:title/


ga_tracking_code: UA-58578580-1
p2pu_ga_tracking_code: UA-55722824-1

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"
  -
    scope:
      path: "articles" # an empty string here means all files in the project
    values:
      layout: "article"
      extra_css: ["/css/article.css"]



prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: 
jumbotron_background_image: "header.jpg"
jumbotron_image:
